In [1]:


if tf.__version__ < "2.0.0":
  !pip install --upgrade tensorflow_gpu==2.0

NameError: name 'tf' is not defined

In [2]:
print(tf.__version__)

NameError: name 'tf' is not defined

In [3]:
#device_name = tf.test.gpu_device_name()
#!apt-get install graphviz -y
#from google.colab import files
#uploaded = files.upload()
import pandas as pd
import io
import tensorflow as tf
import numpy as np

dataframe = pd.read_csv('iris.csv' , header = None)
dataframe

0    1    2    3    4               5
0      1  5.1  3.5  1.4  0.2     Iris-setosa
1      2  4.9  3.0  1.4  0.2     Iris-setosa
2      3  4.7  3.2  1.3  0.2     Iris-setosa
3      4  4.6  3.1  1.5  0.2     Iris-setosa
4      5  5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...  ...             ...
145  146  6.7  3.0  5.2  2.3  Iris-virginica
146  147  6.3  2.5  5.0  1.9  Iris-virginica
147  148  6.5  3.0  5.2  2.0  Iris-virginica
148  149  6.2  3.4  5.4  2.3  Iris-virginica
149  150  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 6 columns]

In [4]:
iris = dataframe.values
iris

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
 

In [5]:
df = dataframe.sample(frac=1)

In [6]:
iris = df.values
iris

array([[107, 4.9, 2.5, 4.5, 1.7, 'Iris-virginica'],
       [63, 6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'],
       [25, 4.8, 3.4, 1.9, 0.2, 'Iris-setosa'],
       [43, 4.4, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [118, 7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [50, 5.0, 3.3, 1.4, 0.2, 'Iris-setosa'],
       [137, 6.3, 3.4, 5.6, 2.4, 'Iris-virginica'],
       [78, 6.7, 3.0, 5.0, 1.7, 'Iris-versicolor'],
       [42, 4.5, 2.3, 1.3, 0.3, 'Iris-setosa'],
       [58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'],
       [45, 5.1, 3.8, 1.9, 0.4, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [31, 4.8, 3.1, 1.6, 0.2, 'Iris-setosa'],
       [101, 6.3, 3.3, 6.0, 2.5, 'Iris-virginica'],
       [131, 7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [129, 6.4, 2.8, 5.6, 2.1, 'Iris-virginica'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [110, 7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [77, 6.8, 2.8, 4.8, 1.4, 'Iris-versico

In [7]:
x_train = iris[:90,:5].astype('float') 
y_train = iris[:90,5]
x_test = iris[90:,:5].astype('float')
y_test = iris[90:,5]
x_train

array([[1.07e+02, 4.90e+00, 2.50e+00, 4.50e+00, 1.70e+00],
       [6.30e+01, 6.00e+00, 2.20e+00, 4.00e+00, 1.00e+00],
       [2.50e+01, 4.80e+00, 3.40e+00, 1.90e+00, 2.00e-01],
       [4.30e+01, 4.40e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [1.18e+02, 7.70e+00, 3.80e+00, 6.70e+00, 2.20e+00],
       [5.00e+01, 5.00e+00, 3.30e+00, 1.40e+00, 2.00e-01],
       [1.37e+02, 6.30e+00, 3.40e+00, 5.60e+00, 2.40e+00],
       [7.80e+01, 6.70e+00, 3.00e+00, 5.00e+00, 1.70e+00],
       [4.20e+01, 4.50e+00, 2.30e+00, 1.30e+00, 3.00e-01],
       [5.80e+01, 4.90e+00, 2.40e+00, 3.30e+00, 1.00e+00],
       [4.50e+01, 5.10e+00, 3.80e+00, 1.90e+00, 4.00e-01],
       [1.90e+01, 5.70e+00, 3.80e+00, 1.70e+00, 3.00e-01],
       [3.10e+01, 4.80e+00, 3.10e+00, 1.60e+00, 2.00e-01],
       [1.01e+02, 6.30e+00, 3.30e+00, 6.00e+00, 2.50e+00],
       [1.31e+02, 7.40e+00, 2.80e+00, 6.10e+00, 1.90e+00],
       [1.29e+02, 6.40e+00, 2.80e+00, 5.60e+00, 2.10e+00],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01

In [8]:
x_train.shape

(90, 5)

In [14]:
y_train

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-set

In [10]:
x_test.shape

(60, 5)

In [11]:
y_test.shape

(60,)

In [2]:
from sklearn.preprocessing import LabelEncoder
# encode class values as integers
le = LabelEncoder()
encoded_Y = le.fit_transform(y_train)
encoded_y_train = tf.keras.utils.to_catagorical(encoded_Y)
encoded_Y = le.fit_transform(y_test)
encoded_y_test = tf.keras.utils.to_catagorical(encoded_Y)

NameError: name 'y_train' is not defined

In [13]:
encoded_y_train


array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1

In [16]:
y_test

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'I

In [17]:
encoded_y_test

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Input(shape=(5,)),
  #tf.keras.layers.Dropout(0.001),
  tf.keras.layers.Dense(8, activation='relu'),
  tf.keras.layers.Dense(3, activation='softmax')
])

In [19]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [38]:
model.fit(x_train , encoded_y_train , epochs=200)

ValueError: Error when checking input: expected input_2 to have shape (4,) but got array with shape (5,)

In [75]:
results = model.evaluate(x_test, encoded_y_test,verbose=2)
results

60/1 - 0s - loss: 0.5410 - accuracy: 0.9500


[0.5317880551020304, 0.95]

In [0]:
i = 40
prediction =  model.predict_classes(x_test[i].reshape(1,4))

In [87]:
if prediction == 0:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-setosa")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])

elif prediction == 1:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-versicolor")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])

else:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-virginica")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])


The data is : [6.1 2.9 4.7 1.4] and I have predicted that it's a [1] i.e Iris-versicolor
Actual data : [6.1 2.9 4.7 1.4] actual label : Iris-versicolor
